# Generated by Django 3.2.5 on 2021-07-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dots',
            name='r_value',
            field=models.IntegerField(verbose_name='R'),
        ),
    ]
